// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_todos_id_ from "./routes/api/todos/[id].ts";
import * as $api_todos_analytics from "./routes/api/todos/analytics.ts";
import * as $api_todos_index from "./routes/api/todos/index.ts";
import * as $api_weather from "./routes/api/weather.ts";
import * as $index from "./routes/index.tsx";
import * as $todos_index from "./routes/todos/index.tsx";
import * as $weather_index from "./routes/weather/index.tsx";
import * as $TodoApp from "./islands/TodoApp.tsx";
import * as $WeatherApp from "./islands/WeatherApp.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/todos/[id].ts": $api_todos_id_,
    "./routes/api/todos/analytics.ts": $api_todos_analytics,
    "./routes/api/todos/index.ts": $api_todos_index,
    "./routes/api/weather.ts": $api_weather,
    "./routes/index.tsx": $index,
    "./routes/todos/index.tsx": $todos_index,
    "./routes/weather/index.tsx": $weather_index,
  },
  islands: {
    "./islands/TodoApp.tsx": $TodoApp,
    "./islands/WeatherApp.tsx": $WeatherApp,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
